#! /bin/sh

bspc monitor -d www dev term misc media

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config history_aware_global_focus true

# Autostart
# ------------------------ #
killall -9 feh polybar sxhkd dunst

feh --bg-fill /home/samsepi0l/animerain.png
sxhkd &
dunst &
setxkbmap latam &
picom --config $HOME/.config/picom/picom.conf &
polybar &
